spring:
  app:
    jwtSecret: mySecretKeyZHVtbXlzZWNyZXRrZXltdXN0YmU2NGRieXRlcw==
    jwtExpirationMs: 86400000
  application:
    name: sb-ecom

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    show-sql: true
    open-in-view: false
#    properties:
#      hibernate:
#        ddl-auto: none
#        format_sql: true
project:
  image: images/