spring:
  app:
    jwtSecret: mySecretKeyZHVtbXlzZWNyZXRrZXltdXN0YmU2NGRieXRlcw==
    jwtExpirationMs: 3600000
    jwtCookieName: ecom_jwt_token
  application:
    name: sb-ecom

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
#    show-sql: true
#    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

project:
  image: images/
#
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate: ERROR